# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Diego Mesa
tagline:          graduate student
url:              http://diego898.github.io/
paginate:         3
baseurl:          http://diego898.github.io/
author:
  name:           Diego Mesa
  url:            http://diego898.github.io/
  email:          diego898@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/diego898/diego898.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about/'
  Articles: '/ia/'
  Topics: '/toi/'
  Archive: '/archive/'
