# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Diego Mesa
tagline:          an academic blog
description:
url:              http://diego898.github.io

author:
  name:           Diego Mesa
  url:            https://diego898.github.io

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/diego898/diego898.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  ToI: '/toi/'